export const WorkTableData = [
    {
        id: 1,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 2,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "LIVE",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: true
    },
    {
        id: 3,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 4,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 5,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "LIVE",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: true
    },
    {
        id: 6,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 7,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 8,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "LIVE",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: true
    },
    {
        id: 9,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 10,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
    {
        id: 11,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "LIVE",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: true
    },
    {
        id: 12,
        message: "My First IVR Flow",
        type: "IVR",
        asignPerson: ["s1.png", "s2.png"],
        status: "DRAFT",
        version: "V1.3",
        text: "Description of workflow comes here in max of two lines with ellipses",
        createdOn: "Jul 20",
        menus: "12",
        exits: "09",
        entries: "02",
        modules: "01",
        deployedStatus: false
    },
]